 version: "3"
 networks:
     fideo-wordpress-net:
         driver: bridge
  
 services:
     mysql:
         image: mysql:5.7
         container_name: fideo-wordpress-6.1.1-mysql
         tty: true
         ports:
             - "4406:3306"
         volumes:
             - "./data/mysql/:/var/lib/mysql"
         environment:
             MYSQL_ROOT_PASSWORD: password
             MYSQL_DATABASE: nombrebasededatos
             MYSQL_USER: nombredeusuario
             MYSQL_PASSWORD: password
         networks:
             - fideo-wordpress-net
  
     server:
         image: wordpress:latest
         container_name: fideo-wordpress-6.1.1
         ports:
             - "8080:80"
         volumes:
             - "./wordpress/:/var/www/html"
         environment:
             WORDPRESS_DB_USER: usuario
             WORDPRESS_DB_PASSWORD: password
             WORDPRESS_DB_NAME: nombrebasededatos
             WORDPRESS_DB_HOST: fideo-wordpress-6.1.1-mysql
         depends_on:
             - mysql
         networks:
             - fideo-wordpress-net
 
      phpmyadmin:
         image: phpmyadmin/phpmyadmin
         container_name: ds-phpmyadmin
         ports:
             - "8081:80"
         environment:
             PMA_HOST: fideo-wordpress-6.1.1-mysql
             MYSQL_ROOT_PASSWORD: password
         depends_on:
             - mysql
          networks:
             - fideo-wordpress-net
